name: 'Configuration Inspector'
type: module
description: 'Provides a configuration data and structure inspector tool.'
package: Development
configure: config_inspector.overview
core_version_requirement: ^8 || ^9
core: 8.x

# Information added by Drupal.org packaging script on 2021-03-12
version: '8.x-1.3'
project: 'config_inspector'
datestamp: 1615550001
